services:
  db:
    image: postgres:16-alpine
    container_name: terminus_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: terminus_dev
    ports:
      - "5432:5432"
    volumes:
      - terminus_pgdata:/var/lib/postgresql/data

volumes:
  terminus_pgdata: