// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Terminus.Infrastructure.Persistence;

#nullable disable

namespace Terminus.Infrastructure.Migrations
{
    [DbContext(typeof(TerminusDbContext))]
    [Migration("20260915185950_AddStatusWaybillsAndContracts")]
    partial class AddStatusWaybillsAndContracts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Terminus.Domain.Entities.Consumer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bank_account");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("consumers", (string)null);
                });

            modelBuilder.Entity("Terminus.Domain.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConclusionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("conclusion_date");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_id");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contract_number");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("ProductId");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("Terminus.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("PriceListNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("price_list_number");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Terminus.Domain.Entities.Waybill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime?>("DispatchDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatch_date");

                    b.Property<int>("ShippedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("shipped_quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("WaybillNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("waybill_number");

                    b.Property<string>("transport_type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("waybills", (string)null);

                    b.HasDiscriminator<string>("transport_type").HasValue("Waybill");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Terminus.Domain.Entities.AutoWaybill", b =>
                {
                    b.HasBaseType("Terminus.Domain.Entities.Waybill");

                    b.Property<decimal>("AutoServiceSum")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("auto_service_sum");

                    b.Property<string>("CarNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("car_number");

                    b.Property<string>("RouteSheetNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("route_sheet_number");

                    b.HasDiscriminator().HasValue("auto");
                });

            modelBuilder.Entity("Terminus.Domain.Entities.AviaWaybill", b =>
                {
                    b.HasBaseType("Terminus.Domain.Entities.Waybill");

                    b.Property<string>("AviaReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("avia_receipt_number");

                    b.Property<decimal>("AviaServiceSum")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("avia_service_sum");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("flight_number");

                    b.HasDiscriminator().HasValue("avia");
                });

            modelBuilder.Entity("Terminus.Domain.Entities.TrainWaybill", b =>
                {
                    b.HasBaseType("Terminus.Domain.Entities.Waybill");

                    b.Property<string>("ContainerNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("container_number");

                    b.Property<string>("RailwayReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("railway_receipt_number");

                    b.Property<decimal>("TrainServiceSum")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("train_service_sum");

                    b.HasDiscriminator().HasValue("train");
                });

            modelBuilder.Entity("Terminus.Domain.Entities.Contract", b =>
                {
                    b.HasOne("Terminus.Domain.Entities.Consumer", "Consumer")
                        .WithMany("Contracts")
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Terminus.Domain.Entities.Product", "Product")
                        .WithMany("Contracts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consumer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Terminus.Domain.Entities.Waybill", b =>
                {
                    b.HasOne("Terminus.Domain.Entities.Contract", "Contract")
                        .WithMany("Waybills")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Terminus.Domain.Entities.Consumer", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("Terminus.Domain.Entities.Contract", b =>
                {
                    b.Navigation("Waybills");
                });

            modelBuilder.Entity("Terminus.Domain.Entities.Product", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
